# Generated by Django 5.0.7 on 2024-07-16 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_status', models.BooleanField(default=True)),
                ('bot_token', models.CharField(max_length=128)),
                ('api_hash', models.CharField(max_length=128)),
                ('api_id', models.CharField(max_length=128)),
                ('bot_username', models.CharField(max_length=128)),
                ('backup_channel', models.BigIntegerField()),
                ('zarin_key', models.CharField(max_length=256)),
                ('checker_key', models.CharField(max_length=256)),
                ('checker_status', models.BooleanField()),
                ('auth_status', models.BooleanField(default=False)),
                ('user_limit_pay', models.BigIntegerField()),
                ('start_text', models.TextField()),
                ('bot_off_text', models.TextField()),
                ('support_text', models.TextField()),
                ('help_text', models.TextField()),
                ('rule_text', models.TextField()),
                ('join_text', models.TextField()),
                ('user_not_active_text', models.TextField()),
                ('user_profile_text', models.TextField()),
                ('privacy_text', models.TextField(default='none')),
                ('channel_1', models.CharField(blank=True, max_length=256, null=True)),
                ('channel_2', models.CharField(blank=True, max_length=256, null=True)),
                ('channel_3', models.CharField(blank=True, max_length=256, null=True)),
                ('channel_4', models.CharField(blank=True, max_length=256, null=True)),
                ('channel_5', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Setting',
            },
        ),
        migrations.CreateModel(
            name='SendMessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('for_all', models.BooleanField(default=True)),
                ('user', models.ManyToManyField(blank=True, related_name='admin_message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SendMessage',
                'verbose_name_plural': 'SendMessages',
            },
        ),
    ]
