# Generated by Django 4.2 on 2024-08-02 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumbersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=128)),
                ('default_price', models.PositiveBigIntegerField()),
                ('price', models.PositiveBigIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('range', models.IntegerField(default=0)),
                ('emoji', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Numbers',
                'verbose_name_plural': 'Numbers',
                'ordering': ['-weight'],
            },
        ),
        migrations.CreateModel(
            name='SettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_status', models.BooleanField(default=True)),
                ('bot_token', models.CharField(max_length=128)),
                ('api_hash', models.CharField(max_length=128)),
                ('api_id', models.CharField(max_length=128)),
                ('session_string', models.TextField(default='none')),
                ('bot_username', models.CharField(max_length=128)),
                ('backup_channel', models.BigIntegerField()),
                ('zarin_key', models.CharField(max_length=256)),
                ('checker_key', models.CharField(max_length=256)),
                ('callino_key', models.CharField(default='none', max_length=256)),
                ('checker_status', models.BooleanField()),
                ('auth_status', models.BooleanField(default=False)),
                ('user_limit_pay', models.BigIntegerField()),
                ('ir_phone_only', models.BooleanField(default=False)),
                ('auth_phone', models.BooleanField(default=False)),
                ('interest_rates', models.PositiveBigIntegerField(default=0)),
                ('number_rows', models.PositiveBigIntegerField(default=10)),
                ('number_timeout', models.PositiveIntegerField(default=5)),
                ('show_numbers', models.CharField(choices=[('active', 'فعال ها'), ('inactive', 'غیر فعال ها'), ('all', 'همه')], default='all', max_length=10)),
                ('start_text', models.TextField(default='متن استارت')),
                ('bot_off_text', models.TextField(default='متن ربات خاموش')),
                ('support_text', models.TextField(default='متن پشتیبانی')),
                ('help_text', models.TextField(default='متن راهنما')),
                ('rule_text', models.TextField(default='متن قوانین')),
                ('join_text', models.TextField(default='متن جوین اجباری')),
                ('user_not_active_text', models.TextField(default='متن کاربر غیر فعال')),
                ('user_profile_text', models.TextField(default='متن زیر پروفایل کاربر')),
                ('privacy_text', models.TextField(default='متن حریم خصوصی')),
                ('approvalـrules', models.TextField(default='متن تایید قوانین ')),
                ('inventory_increase_text', models.TextField(default='متن افزایش موجودی')),
                ('get_user_amount_text', models.TextField(default='متن ارسال مقدار شارژ حساب')),
                ('auth_text', models.TextField(default='متن احراز هویت')),
                ('send_auth_data_text', models.TextField(default='متن ارسال مدارک احراز هویت')),
                ('received_auth_text', models.TextField(default='متن مدارک شما دریافت شد')),
                ('auth_phone_text', models.TextField(default='متن تایید شماره تلفن')),
                ('ir_phone_only_text', models.TextField(default='متن افزایش موجودی فقط با شماره ایرانی')),
                ('inventory_transfer_text', models.TextField(default='متن انتقال موجودی')),
                ('inventory_transfer_error_text', models.TextField(default='متن خطایه انتقال موجودی')),
                ('inventory_transfer_amount_text', models.TextField(default='متن مقدار انتقال موجودی')),
                ('payment_description', models.TextField(default='متن صفحه درگاه پرداخت')),
                ('buy_number_text', models.TextField(default='متن خرید شماره مجازی')),
                ('send_number_to_user_text', models.TextField(default='متن هنگام ارسال شماره به کاربر ')),
                ('user_no_inventory', models.TextField(default='متن کاربر موجودی ندارد !')),
                ('channel_1', models.CharField(blank=True, max_length=256, null=True)),
                ('channel_2', models.CharField(blank=True, max_length=256, null=True)),
                ('channel_3', models.CharField(blank=True, max_length=256, null=True)),
                ('channel_4', models.CharField(blank=True, max_length=256, null=True)),
                ('channel_5', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Setting',
            },
        ),
        migrations.CreateModel(
            name='UserPaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('amount', models.BigIntegerField()),
                ('key', models.CharField(max_length=300)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserPaymnet',
                'verbose_name_plural': 'UserPaymnet',
            },
        ),
        migrations.CreateModel(
            name='UserOrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=55)),
                ('price', models.PositiveIntegerField()),
                ('request_id', models.PositiveIntegerField(default=0)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.numbersmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='SendMessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('for_all', models.BooleanField(default=True)),
                ('user', models.ManyToManyField(blank=True, related_name='admin_message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SendMessage',
                'verbose_name_plural': 'SendMessages',
            },
        ),
        migrations.CreateModel(
            name='InventoryTransferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('tracking_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'InventoryTransfer',
                'verbose_name_plural': 'InventoryTransfer',
            },
        ),
    ]
